In [132]:
from jyquickhelper import add_notebook_menu
add_notebook_menu()

\begin{exercise}

Implement the  neural network example in this notebook with keras

\end{exercise}


# exercise

In [146]:
import tensorflow as tf
from tensorflow import keras

In [147]:
from tensorflow.python.keras.layers import Input, Dense
from tensorflow.python.keras.models import Sequential

In [148]:
def unknown_function(X):
    coeff = np.array([[2., -1., 5.]])
    return np.dot(X, coeff.T)

X = np.array([
    [4.,9.,1.],
    [2.,5.,6.],
    [1.,8.,3.]
])

t = unknown_function(X) # target
print(t)

[[ 4.]
 [29.]
 [ 9.]]


In [149]:
model = tf.keras.Sequential([
  tf.keras.layers.Dense(2, activation='tanh',input_dim=3),  # input required
#   tf.keras.layers.Dense(10, activation="relu"),
  tf.keras.layers.Dense(1)
])
print(model.summary())

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_20 (Dense)             (None, 2)                 8         
_________________________________________________________________
dense_21 (Dense)             (None, 1)                 3         
Total params: 11
Trainable params: 11
Non-trainable params: 0
_________________________________________________________________
None


In [150]:
# Model compilation
# model.compile(loss='mean_squared_error', optimizer='adam')
#SGD better optimizer than adam for our data
model.compile(optimizer='SGD',loss='mean_squared_error') 

In [151]:
def loss(model, x, y):
  y_ = model(x)
  return tf.losses.sparse_softmax_cross_entropy(labels=y, logits=y_)


def grad(model, inputs, targets):
  with tf.GradientTape() as tape:
    loss_value = loss(model, inputs, targets)
  return tape.gradient(loss_value, model.variables)

In [152]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [153]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)

In [154]:

import tensorflow.contrib.eager as tfe
## tensorflow.contrib doesn't exist in 2.0.

ModuleNotFoundError: No module named 'tensorflow.contrib'

In [155]:
model.fit(X , t, epochs=1000)

Train on 3 samples
Epoch 1/1000
3/3 [==============================] - 0s 49ms/sample - loss: 352.1177
Epoch 2/1000
3/3 [==============================] - 0s 1ms/sample - loss: 316.8711
Epoch 3/1000
3/3 [==============================] - 0s 997us/sample - loss: 293.6925
Epoch 4/1000
3/3 [==============================] - 0s 997us/sample - loss: 273.1480
Epoch 5/1000
3/3 [==============================] - 0s 1ms/sample - loss: 254.9783
Epoch 6/1000
3/3 [==============================] - 0s 997us/sample - loss: 238.9169
Epoch 7/1000
3/3 [==============================] - 0s 2ms/sample - loss: 224.7204
Epoch 8/1000
3/3 [==============================] - 0s 2ms/sample - loss: 212.1718
Epoch 9/1000
3/3 [==============================] - 0s 3ms/sample - loss: 201.0793
Epoch 10/1000
3/3 [==============================] - 0s 998us/sample - loss: 191.2738
Epoch 11/1000
3/3 [==============================] - 0s 2ms/sample - loss: 182.6060
Epoch 12/1000
3/3 [==============================] - 0s 9

3/3 [==============================] - 0s 2ms/sample - loss: 116.6769
Epoch 98/1000
3/3 [==============================] - 0s 2ms/sample - loss: 116.6766
Epoch 99/1000
3/3 [==============================] - 0s 998us/sample - loss: 116.6763
Epoch 100/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6761
Epoch 101/1000
3/3 [==============================] - 0s 998us/sample - loss: 116.6759
Epoch 102/1000
3/3 [==============================] - 0s 665us/sample - loss: 116.6757
Epoch 103/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6755
Epoch 104/1000
3/3 [==============================] - 0s 998us/sample - loss: 116.6753
Epoch 105/1000
3/3 [==============================] - 0s 666us/sample - loss: 116.6751
Epoch 106/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6750
Epoch 107/1000
3/3 [==============================] - 0s 2ms/sample - loss: 116.6749
Epoch 108/1000
3/3 [==============================] - 0s 1ms/sample 

3/3 [==============================] - 0s 994us/sample - loss: 116.6708
Epoch 193/1000
3/3 [==============================] - 0s 998us/sample - loss: 116.6708
Epoch 194/1000
3/3 [==============================] - 0s 998us/sample - loss: 116.6708
Epoch 195/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6708
Epoch 196/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6707
Epoch 197/1000
3/3 [==============================] - 0s 998us/sample - loss: 116.6707
Epoch 198/1000
3/3 [==============================] - 0s 2ms/sample - loss: 116.6707
Epoch 199/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6706
Epoch 200/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6706
Epoch 201/1000
3/3 [==============================] - 0s 998us/sample - loss: 116.6706
Epoch 202/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6706
Epoch 203/1000
3/3 [==============================] - 0s 2ms/sampl

3/3 [==============================] - 0s 1ms/sample - loss: 116.6694
Epoch 288/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6694
Epoch 289/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6694
Epoch 290/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6693
Epoch 291/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6693
Epoch 292/1000
3/3 [==============================] - 0s 996us/sample - loss: 116.6693
Epoch 293/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6693
Epoch 294/1000
3/3 [==============================] - 0s 665us/sample - loss: 116.6693
Epoch 295/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6693
Epoch 296/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6693
Epoch 297/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6693
Epoch 298/1000
3/3 [==============================] - 0s 2ms/sampl

3/3 [==============================] - 0s 1ms/sample - loss: 116.6687
Epoch 383/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6687
Epoch 384/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6687
Epoch 385/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6687
Epoch 386/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6687
Epoch 387/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6687
Epoch 388/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6686
Epoch 389/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6686
Epoch 390/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6686
Epoch 391/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6686
Epoch 392/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6686
Epoch 393/1000
3/3 [==============================] - 0s 1ms/sample - 

3/3 [==============================] - 0s 997us/sample - loss: 116.6683
Epoch 478/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6683
Epoch 479/1000
3/3 [==============================] - 0s 991us/sample - loss: 116.6683
Epoch 480/1000
3/3 [==============================] - 0s 5ms/sample - loss: 116.6683
Epoch 481/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6683
Epoch 482/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6683
Epoch 483/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6683
Epoch 484/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6683
Epoch 485/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6683
Epoch 486/1000
3/3 [==============================] - 0s 999us/sample - loss: 116.6683
Epoch 487/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6683
Epoch 488/1000
3/3 [==============================] - 0s 997us/sam

3/3 [==============================] - 0s 1ms/sample - loss: 116.6680
Epoch 573/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6680
Epoch 574/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6680
Epoch 575/1000
3/3 [==============================] - 0s 665us/sample - loss: 116.6680
Epoch 576/1000
3/3 [==============================] - 0s 999us/sample - loss: 116.6680
Epoch 577/1000
3/3 [==============================] - 0s 998us/sample - loss: 116.6680
Epoch 578/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6680
Epoch 579/1000
3/3 [==============================] - 0s 996us/sample - loss: 116.6680
Epoch 580/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6680
Epoch 581/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6680
Epoch 582/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6680
Epoch 583/1000
3/3 [==============================] - 0s 665us/sam

3/3 [==============================] - 0s 665us/sample - loss: 116.6678
Epoch 668/1000
3/3 [==============================] - 0s 2ms/sample - loss: 116.6678
Epoch 669/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6678
Epoch 670/1000
3/3 [==============================] - 0s 2ms/sample - loss: 116.6678
Epoch 671/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6678
Epoch 672/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6678
Epoch 673/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6678
Epoch 674/1000
3/3 [==============================] - 0s 2ms/sample - loss: 116.6678
Epoch 675/1000
3/3 [==============================] - 0s 995us/sample - loss: 116.6678
Epoch 676/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6678
Epoch 677/1000
3/3 [==============================] - 0s 995us/sample - loss: 116.6678
Epoch 678/1000
3/3 [==============================] - 0s 998us/sample 

3/3 [==============================] - 0s 2ms/sample - loss: 116.6677
Epoch 763/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6677
Epoch 764/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6677
Epoch 765/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6677
Epoch 766/1000
3/3 [==============================] - 0s 2ms/sample - loss: 116.6677
Epoch 767/1000
3/3 [==============================] - 0s 2ms/sample - loss: 116.6677
Epoch 768/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6677
Epoch 769/1000
3/3 [==============================] - 0s 2ms/sample - loss: 116.6677
Epoch 770/1000
3/3 [==============================] - 0s 2ms/sample - loss: 116.6677
Epoch 771/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6677
Epoch 772/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6677
Epoch 773/1000
3/3 [==============================] - 0s 998us/sample - 

3/3 [==============================] - 0s 998us/sample - loss: 116.6676
Epoch 858/1000
3/3 [==============================] - 0s 2ms/sample - loss: 116.6676
Epoch 859/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6675
Epoch 860/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6675
Epoch 861/1000
3/3 [==============================] - 0s 996us/sample - loss: 116.6675
Epoch 862/1000
3/3 [==============================] - 0s 2ms/sample - loss: 116.6675
Epoch 863/1000
3/3 [==============================] - 0s 2ms/sample - loss: 116.6675
Epoch 864/1000
3/3 [==============================] - 0s 664us/sample - loss: 116.6675
Epoch 865/1000
3/3 [==============================] - 0s 665us/sample - loss: 116.6675
Epoch 866/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6676
Epoch 867/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6675
Epoch 868/1000
3/3 [==============================] - 0s 665us/sample - 

3/3 [==============================] - 0s 664us/sample - loss: 116.6675
Epoch 953/1000
3/3 [==============================] - 0s 998us/sample - loss: 116.6675
Epoch 954/1000
3/3 [==============================] - 0s 665us/sample - loss: 116.6675
Epoch 955/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6675
Epoch 956/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6674
Epoch 957/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6675
Epoch 958/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6675
Epoch 959/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6674
Epoch 960/1000
3/3 [==============================] - 0s 998us/sample - loss: 116.6674
Epoch 961/1000
3/3 [==============================] - 0s 1ms/sample - loss: 116.6675
Epoch 962/1000
3/3 [==============================] - 0s 997us/sample - loss: 116.6675
Epoch 963/1000
3/3 [==============================] - 0s 665us/sam

In [156]:
print(t)
ypredict =model.predict(X)
print(ypredict)
model.summary(line_length=None, positions=None, print_fn=None)

[[ 4.]
 [29.]
 [ 9.]]
[[13.999996]
 [13.999922]
 [13.999996]]
Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_20 (Dense)             (None, 2)                 8         
_________________________________________________________________
dense_21 (Dense)             (None, 1)                 3         
Total params: 11
Trainable params: 11
Non-trainable params: 0
_________________________________________________________________


# Neural Networks

    

## Structure of Neural Networks

__The neuron__

- The sigmoid equation is what is typically used as a transfer function between neurons. It is similar to the step function, but is continuous and differentiable.

$$ \sigma(x) = \frac{1}{1+e^{-x}}$$

- One useful property of this transfer function is the simplicity of computing its derivative.

$$\frac{d}{dx}\sigma(x) = \sigma' = \sigma(x) (1-\sigma(x))$$

__Single input neuron__

<img src="./image_files/single_neuron.png" width = 300>

$$ O = \sigma(\xi \omega + \theta) $$

__Multiple input neuron__

<img src="./image_files/multiple_neuron.png" width = 300>

$$ O = \sigma(\xi_1 \omega_1 + \xi_2 \omega_2 + \xi_3 \omega_3 +\theta) $$

__A neural network__

<img src="./image_files/nn_03.png" width = 300>

# 2. Learning: Backpropagation Algorithm

__Notation__

- $x_j^\ell$: Input to node $j$ of layer $\ell$

- $W_{ij}^\ell$: Weight from layer $\ell - 1$ node $i$ to layer $\ell$ node $j$

- $\sigma(x) = \frac{1}{1+e^{-x}}$: Sigmoid transfer function

- $\theta_j^{\ell}$: Bias of node $j$ of layer $\ell$

- $O_j^{\ell}$: Output of node $j$ in layer $\ell$

- $t_j$: Target value of node $j$ of the output layer

<br>
<font size='4'><b>The error calculation</b></font>

Given a set of training data points $t_k$ and output layer output $O_k$ we can write the error as

$$ E = \frac{1}{2} \sum_{k \in K} (O_k - t_k)^2$$

We want to calculate $\frac{\partial E}{\partial W_{jk}^{\ell}}$, the rate of change of the error with respect to the given connective weight, so we can minimize it.

Now we consider two cases: the node is an output node, or it is in a hidden layer

__1) Output layer node__

\begin{align*}
\frac{\partial E}{\partial W_{jk}} &= \frac{\partial}{\partial W_{jk}} \frac{1}{2} (O_k - t_k)^2 = (O_k - t_k)\frac{\partial}{\partial W_{jk}} O_k = (O_k - t_k)\frac{\partial}{\partial W_{jk}} \sigma(x_k)\\
&= (O_k - t_k) \sigma(x_k) (1-\sigma(x_k)) \frac{\partial}{\partial W_{jk}} x_k \\
&= (O_k - t_k) O_k (1 - O_k) O_j
\end{align*}

$\quad$For notation purposes, I will define $\delta_k$ to be the expression $(O_k - t_k) O_k (1 - O_k)$, so we can rewrite the equation above as

$$\frac{\partial E}{\partial W_{jk}} = O_j \delta_k $$

__2) Hidden layer node__

\begin{align*}
\frac{\partial E}{\partial W_{ij}} &= \frac{\partial}{\partial W_{ij}} \frac{1}{2} \sum_{k \in K} (O_k - t_k)^2 = \sum_{k \in K} (O_k - t_k)\frac{\partial}{\partial W_{ij}} O_k = \sum_{k \in K} (O_k - t_k)\frac{\partial}{\partial W_{ij}} \sigma(x_k)\\
&= \sum_{k \in K} (O_k - t_k) \sigma(x_k) (1-\sigma(x_k)) \frac{\partial}{\partial W_{ij}} x_k \\
&= \sum_{k \in K} (O_k - t_k) O_k (1 - O_k) \frac{\partial x_k}{\partial O_j}\cdot \frac{\partial O_j}{\partial W_{ij}} = \sum_{k \in K} (O_k - t_k) O_k (1 - O_k) W_{jk}\cdot \frac{\partial O_j}{\partial W_{ij}}\\
&= \frac{\partial O_j}{\partial W_{ij}} \cdot \sum_{k \in K} (O_k - t_k) O_k (1 - O_k) W_{jk}\\
&= O_j (1-O_j)\frac{\partial x_j}{\partial W_{ij}} \cdot \sum_{k \in K} (O_k - t_k) O_k (1 - O_k) W_{jk}\\
&= O_j (1-O_j)O_i \cdot \sum_{k \in K} (O_k - t_k) O_k (1 - O_k) W_{jk}\\
&= O_i O_j (1-O_j) \sum_{k \in K} \delta_k W_{jk}
\end{align*}

$\quad$Similar to before we will now define all terms besides $O_i$ to be $\delta_j = O_j (1-O_j) \sum_{k \in K} \delta_k W_{jk}$, so we have

$$\frac{\partial E}{\partial W_{ij}} = O_i \delta_j$$


__How weights affect errors__

- For an output layer node $k \in K$

$$\frac{\partial E}{\partial W_{jk}} = O_j \delta_k $$

$\quad \;\,$where $$\delta_k = (O_k - t_k) O_k (1 - O_k)$$

- For a hidden layer node $j \in J$

$$\frac{\partial E}{\partial W_{ij}} = O_i \delta_j$$

$\quad \;\,$where $$\delta_j = O_j (1-O_j) \sum_{k \in K} \delta_k W_{jk}$$

__What about the bias?__

If we incorporate the bias term $\theta$ into the equation you will find that

$$ \frac{\partial O}{\partial \theta} = 1$$

This is why we view the bias term as output from a node which is always one. This holds for any layer $\ell$, a substitution into the previous equations gives us that

$$ \frac{\partial E}{\partial \theta} = \delta_{\ell}$$

<br>
<font size='4'><b>The backpropagation algorithm using gradient descent</b></font>

1. Run the network forward with your input data to get the network output

2. For each output node compute
$$\delta_k = (O_k - t_k) O_k (1 - O_k)$$

3. For each hidden node calculate

$$\delta_j = O_j (1-O_j) \sum_{k \in K} \delta_k W_{jk}$$

4. Update the weights and biases as follows<br>

Given

\begin{align*}
\Delta W &= -\eta \delta_{\ell} O_{\ell -1}\\
\Delta \theta &= -\eta \delta_{\ell}
\end{align*}

apply

\begin{align*}
W &\leftarrow W + \Delta W \\
\theta &\leftarrow \theta + \Delta \theta
\end{align*}



In [2]:
%%html
<iframe src="https://www.youtube.com/embed/aVId8KMsdUU?list=PL29C61214F2146796" 
width="560" height="315" frameborder="0" allowfullscreen></iframe>

In [3]:
%%html
<iframe src="https://www.youtube.com/embed/zpykfC4VnpM?list=PL29C61214F2146796" 
width="560" height="315" frameborder="0" allowfullscreen></iframe>

# Implementation in python

## Resources 

- Ian Goodfellow, Yoshua Bengio, and Aaron Courville, [Deep Learning](http://www.deeplearningbook.org/), MIT Press, FREE online copy

- Jason Brownlee **Deep Learning**, available in piazza for this course with codes in `Keras` and `Theano` libraries

- [ml4a chapter on neural networks](http://ml4a.github.io/ml4a/neural_networks/). 

- Michael Nielsen's [Neural Networks and Deep Learning](http://neuralnetworksanddeeplearning.com/), 

- Yoav Goldberg's "[A Primer on Neural Network Models for Natural Language Processing](http://arxiv.org/abs/1510.00726)". 



For the other neural network guides we will mostly rely on the excellent [Keras](http://keras.io/) library, which makes it very easy to build neural networks and can take advantage of [Theano](http://deeplearning.net/software/theano/) or [TensorFlow](https://www.tensorflow.org/)'s optimizations and speed. However, to demonstrate the basics of neural networks, we'll use `numpy` so we can see exactly what's happening every step of the way.

Each unit (neuron) has a vector of weights - these are the parameters that the network learns.

The inner operations of the basic unit is straightforward. We collapse the weight vector $w$ and input vector $v$ into a scalar by taking their dot product. Often a _bias_ term $b$ is added to this dot product; this bias is also learned. then we pass this dot product through an _activation function_ $f$, which also returns a scalar. Activation functions are typically nonlinear so that neural networks can learn nonlinear functions. I'll mention a few common activation functions in a bit, but for now let's see what a basic unit is doing:

```python
def unit(inputs, weights, b):
    return activation_function(np.dot(inputs, weights) + b)
```

Note that the output units often do not have an activation function.

## 3.1. A basic neural network with `numpy`

First we'll import `numpy`:

In [19]:
import numpy as np

With machine learning we are trying to find a hidden function that describes data that we have. Here we are going to cheat a little and define the function ourselves and then use that to generate data. Then we'll try to "reverse engineer" our data and see if we can recover our original function.

In [20]:
def unknown_function(X):
    coeff = np.array([[2., -1., 5.]])
    return np.dot(X, coeff.T)

X = np.array([
    [4.,9.,1.],
    [2.,5.,6.],
    [1.,8.,3.]
])

t = unknown_function(X) # target
print(t)

[[ 4.]
 [29.]
 [ 9.]]


Now we are going to set up our simple neural network. It will have just one hidden layer with two units (which we will refer to as unit 1 and unit 2).

<img src="./image_files/simple_nn_structure.png" width = 250>

First we have to define the weights (i.e. parameters) of our network.

- We have three inputs each going into two units, then one bias value for each unit, so we have eight parameters for the hidden layer.

- Then we have the output of those two hidden layer units going to the output layer, which has only one unit - this gives us two more parameters, plus one bias value.

- So in total, we have eleven parameters.

Let's set them to arbitrary values for now (random initialization).

In [6]:
# initial hidden layer weights
hidden_layer_weights = np.array([
    [0.5, 0.5, 0.5],    # unit 1
    [0.1, 0.1, 0.1]     # unit 2
])
hidden_layer_biases = np.array([1. ,1.])

# initial output layer weights
output_weights = np.array([[1., 1.]])
output_biases = np.array([1.])

We'll use $\tanh$ activations for our hidden units, so let's define that real quick:

In [7]:
def activation(X):
    return np.tanh(X)

$\tanh$ activations are quite common, but you may also encounter sigmoid activations and, more recently, ReLU activations (which output 0 when $x \leq 0$ and output $x$ otherwise). These activation functions have different benefits: 
- ReLUs in particular are robust against training difficulties that come when dealing with deeper networks.

To make things clearer later on, we'll also define the linear function that combines a unit's input with its weights:

In [8]:
def linear(input, weights, biases):
    return np.dot(input, weights.T) + biases

Now we can do a forward pass with our inputs $X$ to see what the predicted outputs are.

## 3.2. Forward pass

First, we'll pass the input through the hidden layer:

In [96]:
hidden_linout = linear(X, hidden_layer_weights, hidden_layer_biases)
hidden_output = activation(hidden_linout)

print('hidden_linout')
print(hidden_output)

hidden_linout
[[ 0.99999978 -0.99905144]
 [ 0.99999939  0.99961695]
 [ 0.99999835 -0.60200848]]


(We're keeping the neuron unit's intermediary value, `hidden_linout` for use in backpropagation.)

Then we'll take the hidden layer's output and pass it through the output layer to get our predicted outputs:

In [10]:
output_linout = linear(hidden_output, output_weights, output_biases)
output_output = output_linout # no activation function on output layer

predicted = output_output
print('predicted')
print(predicted)

predicted
[[2.98367463]
 [2.98009578]
 [2.97574147]]


Now let's compute the mean squared error of our predictions:

In [11]:
mse = np.mean((t - predicted)**2)
print('mean squared error')
print(mse)

mean squared error
238.12000783695962


Now we can take this error and backpropagate it through the network. This will tell us how to update our weights.

## Backpropagation

Since backpropagation is essentially a chain of derivatives (that is used for gradient descent), we'll need the derivative of our activation function, so let's define that first:

In [12]:
def activation_deriv(X):
    return 1 - np.tanh(X)**2

Then we want to set a learning rate - this is a value from 0 to 1 which affects how large we tweak our parameters by for each training iteration.

- You don't want to set this to be too large or else training will never converge (your parameters might get really big and you'll start seeing a lot of `nan` values).

- You don't want to set this to be too small either, otherwise training will be very slow. There are more sophisticated forms of gradient descent that deal with this, but those are beyond the scope of this guide.

In [13]:
learning_rate = 0.001

First we'll propagate the error through the output layer (I won't go through the derivation of each step but they are straightforward to work out if you know a bit about derivatives):

In [14]:
# derivative of mean squared error
error = predicted - t

# delta for the output layer (no activation on output layer)
delta_output = error

# output layer updates
output_weights_update = delta_output.T.dot(hidden_output)
output_biases_update = delta_output.sum(axis=0)

Then through the hidden layer:

In [15]:
# push back the delta to the hidden layer
delta_hidden = delta_output*output_weights*activation_deriv(hidden_linout)

# hidden layer updates
hidden_weights_update = delta_hidden.T.dot(X)
hidden_biases_update = delta_hidden.sum(axis=0)

Then we can apply the updates:

In [16]:
output_weights -= output_weights_update*learning_rate
output_biases -= output_biases_update*learning_rate

hidden_layer_weights -= hidden_weights_update*learning_rate
hidden_layer_biases -= hidden_biases_update*learning_rate

That's one training iteration! In reality, you would do this many, many times - feedforward, backpropagate, update weights, then rinse and repeat. That's the basics of a neural network - at least, the "vanilla" kind. There are other more sophisticated kinds (recurrent and convolutional neural networks are two of the most common) that are covered in other guides.

In [17]:
print (predicted)

[[2.98367463]
 [2.98009578]
 [2.97574147]]


## Combine the above and iterate 

In [18]:
# hidden layer weights
hidden_layer_weights = np.array([
    [0.5, 0.5, 0.5],    # unit 1
    [0.1, 0.1, 0.1]     # unit 2
])
hidden_layer_biases = np.array([1. ,1.])

# output layer weights
output_weights = np.array([[1., 1.]])
output_biases = np.array([1.])

for i in range(1000):
    
    hidden_linout = linear(X, hidden_layer_weights, hidden_layer_biases)
    hidden_output = activation(hidden_linout)
    
    output_linout = linear(hidden_output, output_weights, output_biases)
    output_output = output_linout # no activation function on output layer

    predicted = output_output

    # derivative of mean squared error
    error = predicted - t

    # delta for the output layer (no activation on output layer)
    delta_output = error

    # output layer updates
    output_weights_update = delta_output.T.dot(hidden_output)
    output_biases_update = delta_output.sum(axis = 0)

    # push back the delta to the hidden layer
    delta_hidden = delta_output*output_weights*activation_deriv(hidden_linout)

    # hidden layer updates
    hidden_weights_update = delta_hidden.T.dot(X)
    hidden_biases_update = delta_hidden.sum(axis = 0)

    output_weights -= output_weights_update*learning_rate
    output_biases -= output_biases_update*learning_rate

    hidden_layer_weights -= hidden_weights_update*learning_rate
    hidden_layer_biases -= hidden_biases_update*learning_rate

print (t)    
print (predicted)

[[ 4.]
 [29.]
 [ 9.]]
[[ 5.53744024]
 [26.56337057]
 [ 7.75107771]]
